---
# tasks file for roles/backup

- name: "backup files from remote hoste into local host - {{ backup_host_dir }} ({{ backup_user }})"
  become: true
  become_user: "{{ backup_user }}"
  synchronize:
    src: "{{ item }}"
    dest: "{{ backup_host_dir }}"
    mode: pull
  loop: "{{ backup_remote_dirs | flatten(levels=1) }}"
  tags: backup
